#!/usr/bin/env python3
"""
Windows distribution script for TechTim(e).

This script creates a Windows installer using Inno Setup.

Prerequisites:
- Inno Setup installed (https://jrsoftware.org/isinfo.php)
- ISCC.exe in PATH or specify with --iscc

Usage:
    python scripts/distribute_windows.py
    python scripts/distribute_windows.py --iscc "C:\\Program Files\\Inno Setup 6\\ISCC.exe"
"""
import subprocess
import sys
import shutil
from pathlib import Path


# =============================================================================
# Helper Functions
# =============================================================================

def get_project_root() -> Path:
    """Get project root directory."""
    return Path(__file__).parent.parent


def find_iscc() -> Path:
    """Find the Inno Setup compiler."""
    # Check PATH
    iscc = shutil.which('ISCC')
    if iscc:
        return Path(iscc)
    
    # Check common locations
    common_paths = [
        Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe"),
        Path(r"C:\Program Files\Inno Setup 6\ISCC.exe"),
    ]
    
    for path in common_paths:
        if path.exists():
            return path
    
    return None


# =============================================================================
# Inno Setup Script Generation
# =============================================================================

def create_inno_script(project_root: Path, output_path: Path) -> Path:
    """
    Create an Inno Setup script.
    
    Args:
        project_root: Project root directory
        output_path: Where to write the .iss file
    
    Returns:
        Path to the created script
    """
    app_dir = project_root / 'dist' / 'TechTime'
    
    # Escape backslashes for Inno Setup
    app_dir_str = str(app_dir).replace('\\', '\\\\')
    dist_dir_str = str(project_root / 'dist').replace('\\', '\\\\')
    
    script_content = f'''
; TechTim(e) Inno Setup Script
; Generated by distribute_windows.py

#define MyAppName "TechTime"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "TechTim(e)"
#define MyAppURL "https://github.com/yourusername/techtim"
#define MyAppExeName "TechTime.exe"

[Setup]
AppId={{{{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
OutputDir={dist_dir_str}
OutputBaseFilename=TechTime-Setup-{{#MyAppVersion}}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked

[Files]
Source: "{app_dir_str}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent
'''
    
    output_path.write_text(script_content)
    print(f"Created Inno Setup script: {output_path}")
    
    return output_path


# =============================================================================
# Installer Building
# =============================================================================

def build_installer(iscc_path: Path, script_path: Path) -> bool:
    """
    Build the installer using Inno Setup.
    
    Args:
        iscc_path: Path to ISCC.exe
        script_path: Path to .iss script
    
    Returns:
        True if build succeeded
    """
    print(f"\n{'='*60}")
    print(f"Building installer")
    print('='*60)
    print(f"Compiler: {iscc_path}")
    print(f"Script: {script_path}")
    
    result = subprocess.run(
        [str(iscc_path), str(script_path)],
        capture_output=True,
        text=True,
    )
    
    if result.returncode != 0:
        print(f"\nERROR: Installer build failed")
        print(result.stdout)
        print(result.stderr)
        return False
    
    print("\nInstaller built successfully!")
    return True


# =============================================================================
# Main Entry Point
# =============================================================================

def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Create Windows installer for TechTim(e)'
    )
    parser.add_argument(
        '--iscc',
        type=Path,
        default=None,
        help='Path to ISCC.exe'
    )
    parser.add_argument(
        '--skip-build',
        action='store_true',
        help='Only generate .iss script, do not build'
    )
    
    args = parser.parse_args()
    
    # Check we're on Windows (or allow generating script on other platforms)
    if sys.platform != 'win32' and not args.skip_build:
        print("WARNING: Not on Windows, will only generate .iss script")
        args.skip_build = True
    
    # Get project root
    project_root = get_project_root()
    
    # Check app directory exists
    app_dir = project_root / 'dist' / 'TechTime'
    if not app_dir.exists():
        print(f"ERROR: App directory not found: {app_dir}")
        print("\nRun Phase 4 build first:")
        print("  python scripts/build_app.py")
        sys.exit(1)
    
    # Create script
    script_path = project_root / 'techtim.iss'
    create_inno_script(project_root, script_path)
    
    if args.skip_build:
        print(f"\nInno Setup script created: {script_path}")
        print("Build manually with: ISCC.exe techtim.iss")
        return
    
    # Find Inno Setup
    iscc_path = args.iscc or find_iscc()
    
    if not iscc_path or not iscc_path.exists():
        print("ERROR: Inno Setup not found")
        print("Install from: https://jrsoftware.org/isinfo.php")
        print("Or specify path with --iscc")
        sys.exit(1)
    
    # Build installer
    if not build_installer(iscc_path, script_path):
        sys.exit(1)
    
    # Show result
    installer_path = project_root / 'dist' / 'TechTime-Setup-1.0.0.exe'
    if installer_path.exists():
        size = installer_path.stat().st_size / (1024 * 1024)
        print(f"\n{'='*60}")
        print("Distribution Complete")
        print('='*60)
        print(f"Installer: {installer_path}")
        print(f"Size: {size:.1f} MB")


if __name__ == '__main__':
    main()
